name: app_buscabus
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_local_notifications: ^3.0.1
  flutter_beacon: ^0.3.0
  flutter_blue: ^0.7.2
  date_format: ^1.0.9
  badges: ^1.1.1
  smooth_star_rating: ^1.1.1
  flutter_rating_bar: ^3.0.1+1
  rxdart: ^0.24.1
  geocoder: ^0.2.1
  geolocator: ^6.0.0
  async: ^2.4.1
  json_annotation: ^2.0.0
  flutter:
    sdk: flutter
    
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  google_maps_flutter: ^0.5.31
  flutter_polyline_points: ^0.2.4
  material_design_icons_flutter: 4.0.5555
  flutter_statusbarcolor: ^0.2.3
  http: ^0.12.2
  flutter_staggered_grid_view: ^0.3.2


dev_dependencies:
  build_runner: 
  json_serializable: ^2.0.0
  flutter_test:
    sdk: flutter
    

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
      - assets/fonts/
      - assets/map_style.txt
      - assets/markers/person.png
      - assets/markers/bus.png
      - assets/markers/busStop0.png
      - assets/markers/busStop1.png
      - assets/markers/busStop2.png
      - assets/markers/busStop3.png
      - assets/markers/busStop4.png
      - assets/markers/busStop5.png
      - assets/markers/busStop6.png
      - assets/markers/busStop7.png
      - assets/markers/busStop8.png
      - assets/markers/busStop9.png
      - assets/markers/busStop10.png
      - assets/markers/busStop11.png
      - assets/markers/busStop12.png
      - assets/markers/busStop13.png
      - assets/markers/busStop14.png
      - assets/markers/busStop15.png
      - assets/markers/busStop16.png
      - assets/markers/busStop17.png
      - assets/markers/busStop18.png
      - assets/markers/busStop19.png
      - assets/markers/busStop20.png
      - assets/markers/busStop21.png
      - assets/markers/busStop22.png
      - assets/markers/busStop23.png
      - assets/markers/busStop24.png
      - assets/markers/busStop25.png
      - assets/markers/busStop26.png
      - assets/markers/busStop27.png
      - assets/markers/busStop28.png
      - assets/markers/busStop29.png
      - assets/markers/busStop30.png
      - assets/markers/terminal0.png
      - assets/markers/terminal1.png
      - assets/markers/terminal2.png
      - assets/markers/terminal3.png
      - assets/markers/terminal4.png
      - assets/markers/terminal5.png
      - assets/markers/terminal6.png
      - assets/markers/terminal7.png
      - assets/markers/terminal8.png
      - assets/markers/terminal9.png
      - assets/markers/terminal10.png
      - assets/markers/terminal11.png
      - assets/markers/terminal12.png
      - assets/markers/terminal13.png
      - assets/markers/terminal14.png
      - assets/markers/terminal15.png
      - assets/markers/terminal16.png
      - assets/markers/terminal17.png
      - assets/markers/terminal18.png
      - assets/markers/terminal19.png
      - assets/markers/terminal20.png
      - assets/markers/terminal21.png
      - assets/markers/terminal22.png
      - assets/markers/terminal23.png
      - assets/markers/terminal24.png
      - assets/markers/terminal25.png
      - assets/markers/terminal26.png
      - assets/markers/terminal27.png
      - assets/markers/terminal28.png
      - assets/markers/terminal29.png
      - assets/markers/terminal30.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Abel
      fonts:
        - asset: assets/fonts/Abel-Regular.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Black.ttf
        - asset: assets/fonts/Lato-BlackItalic.ttf
        - asset: assets/fonts/Lato-Bold.ttf
        - asset: assets/fonts/Lato-BoldItalic.ttf
        - asset: assets/fonts/Lato-Italic.ttf
        - asset: assets/fonts/Lato-Light.ttf
        - asset: assets/fonts/Lato-LightItalic.ttf
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Thin.ttf
        - asset: assets/fonts/Lato-ThinItalic.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
        - asset: assets/fonts/Montserrat-BlackItalic.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/Montserrat-ExtraBoldItalic.ttf
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/Montserrat-ExtraLightItalic.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-LightItalic.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
        - asset: assets/fonts/Montserrat-Thin.ttf
        - asset: assets/fonts/Montserrat-ThinItalic.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf 
        - asset: assets/fonts/OpenSans-BoldItalic.ttf 
        - asset: assets/fonts/OpenSans-ExtraBold.ttf 
        - asset: assets/fonts/OpenSans-Italic.ttf 
        - asset: assets/fonts/OpenSans-Light.ttf 
        - asset: assets/fonts/OpenSans-LightItalic.ttf 
        - asset: assets/fonts/OpenSans-Regular.ttf 
        - asset: assets/fonts/OpenSans-SemiBold.ttf 
        - asset: assets/fonts/OpenSans-SemiBoldItalic.ttf 
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-Bold.ttf  
        - asset: assets/fonts/Oswald-ExtraLight.ttf 
        - asset: assets/fonts/Oswald-Light.ttf 
        - asset: assets/fonts/Oswald-Medium.ttf 
        - asset: assets/fonts/Oswald-Regular.ttf 
        - asset: assets/fonts/Oswald-SemiBold.ttf 
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf 
        - asset: assets/fonts/Roboto-BlackItalic.ttf 
        - asset: assets/fonts/Roboto-Bold.ttf 
        - asset: assets/fonts/Roboto-BoldItalic.ttf 
        - asset: assets/fonts/Roboto-Italic.ttf 
        - asset: assets/fonts/Roboto-Light.ttf 
        - asset: assets/fonts/Roboto-LightItalic.ttf 
        - asset: assets/fonts/Roboto-Medium.ttf 
        - asset: assets/fonts/Roboto-MediumItalic.ttf 
        - asset: assets/fonts/Roboto-Regular.ttf 
        - asset: assets/fonts/Roboto-Thin.ttf 
        - asset: assets/fonts/Roboto-ThinItalic.ttf             

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
